au:
  password: shptka_5ade013fd92c76168c566da7e72001db
  theme_id: 124129869958
  store: go-to-skincare.myshopify.com
  ignore_files:
      - config/settings_data.json
      - locales/*.json
      - templates/*.json
      - sections/*.json

staging:
  password: shptka_88612106c9b0965e77f6224ac7c029bc
  theme_id: 130958131356
  store: go-to-staging.myshopify.com
  ignore_files:
      - config/settings_data.json
      - locales/*.json
      - templates/*.json
      - sections/*.json
